version: '3.9'
services:
  edgedb-api:
    build: 
      context: .
      dockerfile: ./docker/edgedb-api/Dockerfile
    volumes:
      - ./edgedb-api/:/app/
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000